on:
  push:
    branches:
    - master
    paths:
    - 'runner/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Login DockerHub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u sminamot --password-stdin
    - name: Push container image
      run: make docker-push
      working-directory: runner
