on:
  push:
    branches:
    - master
    paths-ignore:
    - 'runner/**'
    - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Install kubebuilder
      run: |
        curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.2.0/kubebuilder_2.2.0_linux_amd64.tar.gz
        tar zxvf kubebuilder_2.2.0_linux_amd64.tar.gz
        sudo mv kubebuilder_2.2.0_linux_amd64 /usr/local/kubebuilder
    - name: Run tests
      run: make test
    - name: Login DockerHub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u sminamot --password-stdin
    - name: Build and Push container image
      run: make docker-push
